# Create a persistent volume with name app-data, of capacity 2Gi and access mode ReadOnlyMany. The type of volume is hostPath and its location is /srv/app- data.
# DOCS: Configure a Pod to Use a PersistentVolume for Storage

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    type: hostPath
spec:
  #storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/srv/app"